### ISSUE TITLE
Release (probably) contains malware

### ISSUE THREAD

**Issue by catnotadog** [Xytriza/gd-save-editor#3]
bro, really?

**Comment by Xytriza** [comment]
entire source code posted in https://github.com/Xytriza/gd-save-editor/tree/client

you can also debug network traffic and everything if you dont feel comfortable

**Comment by Xytriza** [comment]
the only traffic that will be showing up is github.com due to this being "auto updater"

**Comment by Xytriza** [comment]
if you have any evidence to prove this please provide it here

1.0.1 only fetched github.com - you can verify this with a network debugger
1.0.1 also updated automatically so you don't have to download the exe multiple times - reverted in 1.0.2

and it seems like your just throwing it out here because nuitka flagged your microsoft defender, which it does for all exes compiled in nuitka (try it yourself)

**Comment by Xytriza** [comment]
1.0.2 also uses my server for fetching new updates as its easiest for me to publish to.
